<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_username_dynamic</name>
   <tag></tag>
   <elementGuidId>dc70305d-a96a-4957-8895-58a0c257c892</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//button[@id='single-button']//span)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//button[@id='single-button']//span)[2]</value>
      <webElementGuid>d3b17bfb-0a27-489c-ac0c-dab85f74d4e7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
