<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_sidebar_menu_dashboard</name>
   <tag></tag>
   <elementGuidId>673c6fd2-13d2-4ef4-8383-f84fcf4e8106</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[text()='Dashboard']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[text()='Dashboard']</value>
      <webElementGuid>6db4a86e-dcc2-4d08-817c-764eca362836</webElementGuid>
   </webElementProperties>
</WebElementEntity>
